# Generated by Django 4.0.4 on 2022-06-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
