# Generated by Django 4.0.4 on 2022-06-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='back.category'),
        ),
    ]
